# [BungeeCord settings]
# If you use BungeeCord you need to set this to true and
# you don't need to set any settings here. Message managing is still enabled
# and it's more effective that you use this settings if you use some other
# chat managing plugin.
bungeecord: true

# [Bot settings]
guild_id: 814671813032411156
discord_channel_id: 814671928249286676

# [Player count settings]
# If you want to display player count on the discord bot.
show_players_online: true
# Set costume display. <number> will be replaced 
# with number of players playing on the server.
bot_playing_text: 'Currently <number> of players playing on the server!'
# Status: DEFAULT, LISTENING, STREAMING, WATCHING
bot_status: DEFAULT

# [Chat Minecraft]
# <name> will be replaced with the discord user name.
# <message> will be replaced with the message from discord message.
# <role> will be replaced with the higest role from discord.
minecraft_chat: '<role> <<name>> <message>'
server_start: '<server> server has started'
server_stop: '<server> server has stopped'
use_minecraft_nicknames: false

# [Chat Discord]
# <name> will be replaced with the minecraft user name.
# <message> will be replaced with the message from minecraft chat.
discord_chat: '**<name>** <message>'
use_discord_nicknames: true
# If false users from discord can't use color codes.
colorcodes_enabled: false

# [Join and leave messages]
discord_joined_message_enabled: true
discord_left_message_enabled: true
# Message structure when a player joines the network.
# <name> will be replaced with the minecraft user name
discord_joined_message: '**<name> joined the game**'
discord_left_message: '**<name> left the game**'
# Border (Embed) for Join messages
use_fancy_border: true
# Select the color of the border:
builder_color: f8fc19

# [Message managing]
# Use this to ban words in messages.
# This will not display a message if it contains a sequence of text.
# list_of_banned_words, list_of_banned_prefixes, list_of_banned_format_words
# and list_of_banned_format_prefixes are string lists.
# Example of how the format should look:
# list_of_banned_words:
# - 'Some sequence of text'
# - 'Another sequence'
list_of_banned_words:

list_of_banned_prefixes:

list_of_banned_format_words:

list_of_banned_format_prefixes:

# [Other messages]
# This message will be displayed on the main discord channel
# To use this. It has to be enabled on the spigot server.

# Manely used to see the formats of the messages.
debug_mode: false

backpacks: 0