# Plugin made by alandioda [BungeeCord]

# [Bot settings]
TOKEN: ODE0NjcyMjYxODM0NDczNTMy.YDhQqw.YyltuP1kCiKhZBu42kqY_UuKOvU
guild_id: 814671813032411156
discord_channel_id: 814671928249286676
# If you want to use only this bot on the bungeecord.
use_only_bungeecord: false

# [Player count settings]
# If you want to display player count on the discord bot.
show_players_online: true
# Set costume display. <number> will be replaced 
# with number of players playing on the network.
bot_playing_text: 'Currently <number> of players playing on the network!'
# Status: DEFAULT, LISTENING, STREAMING, WATCHING
bot_status: DEFAULT

# [Chat Minecraft]
# <name> will be replaced with the discord user name.
# <message> will be replaced with the message from discord message.
# <role> will be replaced with the higest role from discord.
minecraft_chat: '<role> <<name>> <message>'
use_minecraft_nicknames: false

# [Chat Discord]
# <name> will be replaced with the minecraft user name.
# <message> will be replaced with the message from minecraft chat.
discord_chat: '**<name>** <message>'
use_discord_nicknames: true
# If false users from discord can't use color codes.
colorcodes_enabled: false

# [Join and leave messages]
discord_joined_message_enabled: true
discord_left_message_enabled: true
# Message structure when a player joines the network.
# <name> will be replaced with the minecraft user name
discord_joined_message: '**<name> joined the game**'
discord_left_message: '**<name> left the game**'
# Border (Embed) for Join messages
use_fancy_border: true
# Select the color of the border:
builder_color: f8fc19