name: MFC
main: ac.minef.mfc.spigot.MFC
version: 1.0-SNAPSHOT
depend:
  - LiteBans
  - Sparky
commands:
  vote:
    aliases:
      - votes
      - voting
      - votelink
      - votelinks
  mfc:
    aliases:
      - core
      - mfcore
      - minefacore
      - minefaccore
