name: MFC
main: ac.minef.mfc.spigot.MFC
version: 1.0-SNAPSHOT
depend:
  - DiscordBotAPI
  - LiteBans
  - Sparky
commands:
  mfc:
    aliases:
      - core
      - mfcore
      - minefacore
      - minefaccore
